Taipei-yp/taipei-runner

client/components/textarea/index.tsx, client/components/textarea/textarea.css, client/components/textarea/textarea.tsx
=> Sprint_1.Task_3.0.7: add textarea component

client/components/panel/index.tsx, client/components/panel/panel.css, client/components/panel/panel.tsx
=> Sprint_1.task_3.0.13: add panel component

.eslintrc, client/components/button/button.tsx, client/components/form-field/form-field.css, client/components/form-field/form-field.tsx, client/components/form-field/index.tsx, client/components/form-view/form-view.css, client/components/form-view/form-view.tsx, client/components/form-view/index.tsx, client/components/input/index.tsx, client/components/input/input.css, client/components/input/input.tsx, client/pages/signup/index.tsx, client/pages/signup/signup.css, client/pages/signup/signup.tsx, package-lock.json, package.json
Sprint_1.task_3.0.3: add formField component
Sprint_1.task_3.02: add form component
Sprint_1.task_3.1: add signUp page
Closes #12 
Closes #24 
Closes #23
=> Sprint_1.task_3.1: add SignUp page

client/components/header/header.css, client/components/header/header.tsx, client/components/header/index.tsx
=> Sprint_1.task_3.0.10: add Header component

client/components/link-view/index.ts, client/components/link-view/link-view.css, client/components/link-view/link-view.tsx
=> link-view component

.eslintrc, client/app.tsx, client/components/table/index.tsx, client/components/table/table-sort.ts, client/components/table/table.css, client/components/table/table.tsx, client/pages/forum/forum.tsx, client/pages/forum/index.ts
=> Table component

client/app.tsx, client/pages/signin/index.tsx, client/pages/signin/signin.css, client/pages/signin/signin.tsx, client/pages/signup/signup.css, client/pages/signup/signup.tsx
Добавлена страница авторизации. Попутно заменил на странице регистрации заголовок нашим компонентом. 
Closes #13
=> Sprint_1.task_3.2: add signIn page

client/app.tsx, client/components/link-view/link-view.css, client/components/link-view/link-view.tsx, client/pages/menu/index.tsx, client/pages/menu/menu.css, client/pages/menu/menu.tsx, client/styles/variables.css
За одно немного зарефакторил компонент LinkView
Closes #17
=> Sprint_1.task_3.5: add menu page

client/app.tsx, client/components/avatar/avatar.tsx, client/components/form-view/form-view.tsx, client/components/forum-msg/forum-msg.css, client/components/forum-msg/forum-msg.tsx, client/components/forum-msg/index.tsx, client/components/private-route/private-route.tsx, client/index.html, client/models/msg.ts, client/pages/forum-topic/forum-topic.css, client/pages/forum-topic/forum-topic.tsx, client/pages/forum-topic/index.tsx
=> Sprint_1.Task_3.0.16: add forum topic page

.eslintrc, client/components/table/index.tsx, client/components/table/table-sort.ts, client/components/table/table.tsx, client/components/table/types.ts
=> Sprint_1.task_0.1: fix table type export warnings

client/components/form-field/form-field.css, client/components/input/input.css, client/components/table/table.css, client/styles/style.css
=> Sprint_1.task_3.0.18: add font-size variables to all components

client/components/heading/heading.css, client/pages/error/error.css, client/pages/gameover/gameover.css, client/pages/gameover/gameover.tsx, client/pages/gameover/index.tsx, client/utils/format-score.ts
=> Sprint 1 task 3.6 Gameover page

client/app.tsx, client/components/background/background.css, client/components/page/page.css, client/components/score-counter/score-counter.tsx, client/pages/error/error.tsx, client/pages/forum-topic/forum-topic.tsx, client/pages/game/game.tsx, client/pages/gameover/gameover.tsx, client/pages/profile/profile.tsx
Использовал функцию форматирования счета в компоненте счетчика;
Изменил путь до компонента Menu на / в роутингах и на страницах;
=> Sprint 1.fix 1 

client/app.tsx, client/components/form-field/form-field.css, client/components/form-field/form-field.tsx, client/components/form-view/form-view.css, client/components/form-view/form-view.tsx, client/components/input/input.css, client/components/input/input.tsx, client/components/page/page.css, client/components/textarea/textarea.css, client/components/textarea/textarea.tsx, client/pages/feedback/feedback.css, client/pages/feedback/feedback.tsx, client/pages/feedback/index.ts, client/pages/forum-topic/forum-topic.tsx, client/pages/menu/menu.tsx
=> Sprint 1 task 3.0.17: add feedback page

.eslintrc, client/api/api.ts, client/api/auth-api.ts, client/components/avatar/avatar.tsx, client/components/form-view/form-view.tsx, client/components/forum-msg/forum-msg.tsx, client/components/page/page.tsx, client/components/pagination/pagination.tsx, client/components/score-counter/score-counter.tsx, client/components/table/table-sort.ts, client/components/table/table.tsx, client/components/user/user.tsx, client/game-engine/hero.ts, client/game-engine/horizon.ts, client/game-engine/obstacle.ts, client/pages/error/error.tsx, client/pages/feedback/feedback.tsx, client/pages/forum-topic/forum-topic.tsx, client/pages/forum/forum.tsx, client/pages/game/game.tsx, client/pages/gameover/gameover.tsx, client/pages/leaderboard/leaderboard.tsx, client/pages/menu/menu.tsx, client/pages/profile/profile.tsx, client/pages/signin/signin.tsx, client/pages/signup/signup.tsx, client/services/auth/use-auth-service.ts, client/utils/array-utils.ts, client/utils/ui-types.ts, tsconfig.json
=> sprint_2 task_f3,f10 refactor imports

client/app.tsx, client/pages/signin/signin.css, client/pages/signin/signin.tsx, client/pages/signup/signup.css, client/pages/signup/signup.tsx, client/services/auth/index.ts, client/services/auth/types.ts, client/services/auth/use-auth-service.ts
Фиксы с ревью Юры
Closes #87
Closes #88
Closes #89 
Closes #90 
Closes #91 
Closes #92
=> f4,f5,f6,f7,f8,f8: useAuthService pr fixes

client/redux/forum/forum-reducer.tsx, client/redux/initial-state.tsx, client/redux/leaderboard/leaderboard-reducer.tsx, client/redux/root-reducer.tsx, client/redux/store.tsx, client/redux/user/user-reducer.tsx, package-lock.json, package.json
=> add redux; redux catalog;

client/index.tsx, client/pages/feedback/feedback.tsx, client/redux/auth/auth-reducer.tsx, client/sw.ts, webpack/webpack.base.js, webpack/webpack.prod.js
=> Sprint 2.task 15

client/components/header/header.test.tsx, client/game-engine/audio.ts, client/game-engine/horizon.ts, client/game-engine/runner.ts, client/pages/game/game.tsx
Пофиксил перезапуск игры (текстуры, и звук).
Но по-хорошему нужно еще разбираться со звуками, так как у меня до первого проигрыша музыка не играет (остальные звуки есть). Думаю это не так критично
=> Sprint_2.hot-fixies: game restart fixies

Dockerfile
Добавил в докер гит, так как он используется при сборке.
=> Sprint_2.docker-fix: docker fix (add git)

client/game-engine/audio.ts, client/pages/game/game.tsx
Убрал useRef потому что при обновлении счетчика создавались объекты runner
=> audio bg fix

client/game-engine/runner.ts
=> Gamepad api
